export const LIST_BAD_CHARACTERS = 'LIST_BAD_CHARACTERS';
export const LIST_BAD_FAVOURITE = 'BAD_FAVOURITE';
export const ADD_BAD_FAVOURITE = 'ADD_BAD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';
